# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Temp\vscode\swesim_landlab\ui_elements\swesim_gis_projection_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(250, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(250, 150))
        Dialog.setMaximumSize(QtCore.QSize(250, 203))
        Dialog.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.grpSelectProjection = QtWidgets.QGroupBox(Dialog)
        self.grpSelectProjection.setMinimumSize(QtCore.QSize(150, 100))
        self.grpSelectProjection.setObjectName("grpSelectProjection")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.grpSelectProjection)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mQgsProjectionSelectionWidget = QgsProjectionSelectionWidget(self.grpSelectProjection)
        self.mQgsProjectionSelectionWidget.setMaximumSize(QtCore.QSize(16777215, 25))
        self.mQgsProjectionSelectionWidget.setObjectName("mQgsProjectionSelectionWidget")
        self.verticalLayout.addWidget(self.mQgsProjectionSelectionWidget)
        self.verticalLayout_2.addWidget(self.grpSelectProjection)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.btnOK = QtWidgets.QPushButton(Dialog)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout_5.addWidget(self.btnOK)
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_5.addWidget(self.btnCancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.grpSelectProjection.setTitle(_translate("Dialog", "Select Projection:"))
        self.btnOK.setText(_translate("Dialog", "OK"))
        self.btnCancel.setText(_translate("Dialog", "Cancel"))
from qgsprojectionselectionwidget import QgsProjectionSelectionWidget
